# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.metric import Metric  # noqa: F401,E501
from swagger_server import util


class Metrics(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, list: List[Metric]=None, time_ms: int=None):  # noqa: E501
        """Metrics - a model defined in Swagger

        :param list: The list of this Metrics.  # noqa: E501
        :type list: List[Metric]
        :param time_ms: The time_ms of this Metrics.  # noqa: E501
        :type time_ms: int
        """
        self.swagger_types = {
            'list': List[Metric],
            'time_ms': int
        }

        self.attribute_map = {
            'list': 'list',
            'time_ms': 'time_ms'
        }

        self._list = list
        self._time_ms = time_ms

    @classmethod
    def from_dict(cls, dikt) -> 'Metrics':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Metrics of this Metrics.  # noqa: E501
        :rtype: Metrics
        """
        return util.deserialize_model(dikt, cls)

    @property
    def list(self) -> List[Metric]:
        """Gets the list of this Metrics.

        List of metric objects  # noqa: E501

        :return: The list of this Metrics.
        :rtype: List[Metric]
        """
        return self._list

    @list.setter
    def list(self, list: List[Metric]):
        """Sets the list of this Metrics.

        List of metric objects  # noqa: E501

        :param list: The list of this Metrics.
        :type list: List[Metric]
        """

        self._list = list

    @property
    def time_ms(self) -> int:
        """Gets the time_ms of this Metrics.

        Time when metrics were taken (milliseconds since epoch)  # noqa: E501

        :return: The time_ms of this Metrics.
        :rtype: int
        """
        return self._time_ms

    @time_ms.setter
    def time_ms(self, time_ms: int):
        """Sets the time_ms of this Metrics.

        Time when metrics were taken (milliseconds since epoch)  # noqa: E501

        :param time_ms: The time_ms of this Metrics.
        :type time_ms: int
        """

        self._time_ms = time_ms
